apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  openai-base-url: http://ollama-model-traveldiscover:11434/v1
  openai-model: llama3
  allow-origins: "https://traveldiscover.fr"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traveldiscover-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traveldiscover-backend
  template:
    metadata:
      labels:
        app: traveldiscover-backend
    spec:
      containers:
      - name: traveldiscover-backend
        image: docker.io/lpicode/traveldiscover-backend:0.1.3 # {"$imagepolicy": "flux-system:traveldiscover-backend"}
        ports:
        - containerPort: 4200
        resources:
          requests:
            cpu: "400m"
            memory: "128Mi"
          limits:
            cpu: "800m"
            memory: "256Mi"
        env:
        - name: AMADEUS_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: amadeus-api-key
        - name: AMADEUS_API_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: amadeus-api-secret
        - name: HERE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: here-api-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: openai-api-key
        - name: OPENAI_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: openai-base-url
              optional: true
        - name: ALLOW_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: allow-origins
              optional: true
        - name: OPENAI_MODEL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: openai-model
              optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: traveldiscover-backend
spec:
  selector:
    app: traveldiscover-backend
  ports:
  - port: 4200
    targetPort: 4200
  type: ClusterIP
