apiVersion: v1
kind: Service
metadata:
  name: td-backend-service
  namespace: default
spec:
  selector:
    app: td-backend
  ports:
  - name: http-back
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
