apiVersion: v1
kind: Service
metadata:
  name: td-backend
  namespace: default
spec:
  selector:
    app: td-backend
  ports:
  - name: http-back
    protocol: TCP
    port: 4200
    targetPort: 4200
  type: ClusterIP
