
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: contact@traveldiscover.fr # replace for your valid email
    privateKeySecretRef:
      name: le
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik