apiVersion: v1
kind: Service
metadata:
  name: td-frontend-service
  namespace: default
spec:
  selector:
    app: td-frontend
  ports:
  - name: http-front
    protocol: TCP
    port: 4200
    targetPort: 4200
  type: ClusterIP
