resources:
  - cloudflared.yaml
  - ui.yaml
  - namespace.yaml
  - llm.yaml
  - api.yaml
  - grafana.yaml

configMapGenerator:
  - name: cloudflared
    files:
      - tunnel-config.yaml

namespace: traveldiscover