---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: traveldiscover-frontend
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/lpicode/TravelDiscoverManifest
  ref:
    branch: main
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: traveldiscover-frontend
spec:
  imageRepositoryRef:
    name: traveldiscover-frontend
  policy:
    semver:
      range: '>=0.1.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: traveldiscover-frontend
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./base/traveldiscover
    strategy: Setters
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traveldiscover-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traveldiscover-frontend
  template:
    metadata:
      labels:
        app: traveldiscover-frontend
    spec:
      containers:
      - name: traveldiscover-frontend
        image: docker.io/lpicode/traveldiscover-frontend:0.1.0 # {"$imagepolicy": "traveldiscover:traveldiscover-frontend"}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "400m"
            memory: "128Mi"
          limits:
            cpu: "800m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: traveldiscover-frontend
spec:
  selector:
    app: traveldiscover-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP