apiVersion: apps/v1
kind: Deployment
metadata:
  name: traveldiscover-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traveldiscover-frontend
  template:
    metadata:
      labels:
        app: traveldiscover-frontend
    spec:
      containers:
      - name: traveldiscover-frontend
        image: docker.io/lpicode/traveldiscover-frontend:0.1.3 # {"$imagepolicy": "flux-system:traveldiscover-frontend"}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "400m"
            memory: "128Mi"
          limits:
            cpu: "800m"
            memory: "256Mi"
        env:
        - name: API_URL
          value: "https://api.traveldiscover.fr"
---
apiVersion: v1
kind: Service
metadata:
  name: traveldiscover-frontend
spec:
  selector:
    app: traveldiscover-frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
