apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 10m
  path: "./overlays/production"
  prune: true
  sourceRef:
    kind: GitRepository
    name: traveldiscover-repo
  targetNamespace: traveldiscover-production
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 10m
  path: "./overlays/staging"
  prune: true
  sourceRef:
    kind: GitRepository
    name: traveldiscover-repo
  targetNamespace: traveldiscover-staging
