apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traveldiscover-dev
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: '5m0s'
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traveldiscover-prod
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: '5m0s'
  validation: client