apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: flux-system
spec:
  encryptedData:
    credentials.json: AgBcv8ZABkxBFS8yWkMPvXfkiqoFBmVeFS1mI41o1XTEjVQsGXr1/m5vgvW548MlHrMdQC/AMvy16ppzWKD0ZhGOywLhZ+uK4Gzxov4WyQO8ZRfmAzKkdl0dVHCl3Ayzf2VQa0WtroFfIQ26W5Np+dz3E67T4wBL9khSb6sLf1jSFtahYcB7qIjyQCyo033F1y/lo4kfJlLHtz82kd2NzGmBjXxcWr6ZtUp1VXWwA3SiairZUJF26qME4vt3VPmKmO5ranMcOYTpp4Ded00rGRoVTbkF72HVy3qW76bRJHb/B80LFSB2uaPoBcdsqNzi1Q/1jSfvPikEEZ0jUONMC0rnUHDxE5tjTzVWW9cmSaJAu8gjnZMR1ZVu/I+0Jvqfsi4RUjNa9wS8IiW60BytD9YBusNzUGoDqOaIKjf7ZJnzPAoqIT9oByGIGAePqG0Da2olULXKt7ndN12CDnDssfqm6/ZRu1Ep/eFVwNFLFUlaXJc/z4KUwXaInr2tuKOk9MxD3atUayZd2lk6sLER0ZqIPSd+3uG0yrdxhTLxoY4sBD8NIqXh+Xz9YK6vCDKy4AgdcklGXDCwYw9N/wmfMMxUT7jCLv6D+kByjPicVnJYKXtIaQ7ISVSZZvgChWEzFFHRNP1O7ADPEV3G6g0cz00qFqDY1T04zYEvzkQbw11hy3QtnkqMPbnIXbNW0OvpIG0jLn5vRQbakWIU0VFetDjNeMO5n+DK7RkgVH8I9PiI2oU07O9cacqKljhtsOZKiXz7hp2ck95MicxKbnVsHHaipAmkVLB2e5yM1XFV6Q0bLWoCgVQhFRlXXJwwkQjAImqztfKzCB1VKr/bgtxfEGS18/dQD0h9id4GI2xwGGL2vBw7DcKpg0+hMnDBgBZB427QapB77Dt7FMvGudiUdfkjKw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: traveldiscover