resources:
  - ../../base
  - frontend-ingress.yaml
  - backend-ingress.yaml

patchesStrategicMerge:
  - patches.yaml

images:
  - name: lpicode/traveldiscover-frontend:latest
    newTag: dev
  - name: lpicode/traveldiscover-backend:latest
    newTag: dev