resources:
  - ../../base/frontend-deployment.yaml
  - ../../base/backend-deployment.yaml
  - ../../base/frontend-service.yaml
  - ../../base/backend-service.yaml
  - frontend-ingress.yaml
  - backend-ingress.yaml

namespace: traveldiscover-dev

patchesStrategicMerge:
  - patches.yaml

images:
  - name: lpicode/traveldiscover-frontend:latest
    newTag: dev
  - name: lpicode/traveldiscover-backend:latest
    newTag: dev