resources:
  - ../../base
  - frontend-ingress.yaml
  - backend-ingress.yaml

namespace: traveldiscover-dev
namePrefix: dev-

images:
  - name: lpicode/traveldiscover-frontend:latest
    newTag: dev
  - name: lpicode/traveldiscover-backend:latest
    newTag: dev