resources:
  - ../../base
  - frontend-ingress.yaml
  - backend-ingress.yaml
  - ../../base/frontend-deployment.yaml
  - ../../base/backend-deployment.yaml

images:
  - name: lpicode/traveldiscover-frontend:latest
    newTag: latest
  - name: lpicode/traveldiscover-backend:latest
    newTag: latest