apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend-ingress.yaml
  - backend-ingress.yaml

bases:
  - ../../base
namespace: traveldiscover

patchesStrategicMerge:
  - patches.yaml

images:
  - name: lpicode/traveldiscover-frontend:latest
    newTag: latest
  - name: lpicode/traveldiscover-backend:latest
    newTag: latest