apiVersion: apps/v1
kind: Deployment
metadata:
  name: td-frontend
  namespace: traveldiscover
spec:
  replicas: 1 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: td-backend
  namespace: traveldiscover
spec:
  replicas: 1
