---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBiuDxF7aztg/3I9rGybUamdN5E9T+onDYzbi+KcKymI2nsGB/s+oCK5sF7i0nWEkEG2k1tMyXGS4nsbpHl6GTHp0Ow8rBg6VnB0eoRh0rev0JJKJYNOZE1l/UDjW3ZDPgOLCc+Wriy+DqTk1wPe18d7h6RUrpvpSqpBn6axEm+9Ox+fFivaeDNe3aate/D8Uu+C/kGOnoW2aC1YWB8Kd68XeBA1wjQBypzPNC3S7j9Lwpb7s6P/DnZHNchKMbDWeWcfo/rIx/m+j78BHLa1PqMUOttaaPvDWUDvwKxbkiAHgtd3L2WlzLsukASpzTjpIMAA2U3OOoA9khlvkT8j1RomfZZeftr/QMBNAYpfHWcIXv5hnrGmep795Gqzuqx+SisfVrryp5ia6yeUkgrffY32w6E5ra1TB9TAt9rNFwT5/xkfSFu1QQkvZBslK4ahbQdtKxMFJ4tcEbSbdjkZJDxRgEYGs4Kr7jYOdOJuz34iPUfQ1SFkK842m3abIGiAWp6oc4pRBwoK1s36qr4AuuSAzsBpDOinJLnblbuLFR+/KA6VeuM0w+JlRtVHXuXlXTOD6PxujUnPuk86BKJSYcUlYsm4D/yHM50eegcVcCctd4mwbljgpIyi2DgajCv0vRKBc07UtQLj1OMcGImXSu9zTw1BuVtMjO7uaSLgkM53wFRMiywY2HdCC05c8LXXw/6zyHtZVs5JMdQKZdNYYZETjDoaJMsL0256IAMDlNjhSyFpXHoQedY55i5Dqomg/1Ib3RocHwX8RDV3eqdWvd1z92CVDmZov5MzlBofWmwN15liMidDm+nskqzrFQ2Bq9atDySrQ5btAjOL4VgyT01Xt6MJQK9FhcfNP81Gxl4PNsvd2eDw0ltT8k/kjwy1w6Bbis8m54Acys8KbFDiInpqQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared