---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: traefik
spec:
  encryptedData:
    credentials.json: eyJBY2NvdW50VGFnIjoiNmZiY2RjNzk0ZjI0NzI0ZjU3NjUyYWZkZTcxNTU3MmEiLCJUdW5uZWxTZWNyZXQiOiJreC9qcDFqMmxTc0wxZmxWYkVvRlU2eU5YTllEcG1veWlZQnNJckdrUHNFPSIsIlR1bm5lbElEIjoiODU0MjcxZDMtZWRmZC00OWYyLTlmOTQtYjU1NGEzNDM5NzM4In0=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: traefik