apiVersion: apps/v1
kind: Deployment
metadata:
  name: td-frontend
spec:
  replicas: 1 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: td-backend
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: td-frontend-service
spec:
  selector:
    app: td-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: td-backend-service
spec:
  selector:
    app: td-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP