---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCWt18GShOttP9fHlByi6g64FiuEuS/00xs9Nm2a6Zxwhiu2/XdQfDwN155x6WXSyrz9lPTvonqsFvHUKn6U3ya3WMxyD1XFk4kvoN3GqYW6mOLk23e/Lu9HQXatmlUq/8o5OQWD/V2t9LeLI4C8SEMy74JMSo8iCvK0Qyzv06lLi0YjjPrGNp8f8Nc0lVf10bPSMS6HqJjd1YhPp/UbttIAKgzMUqxP3hwEiJPyNzbiXpn4vINGdPUP7xPz8/WW5UDTs5OBkGOoNaEwuLi7Tw4LrBqLFw7mG4+iDdlMQP2q6ZZQd9G7bhhWl10iEaz7OLqtWOCI6yNVw0S5JL9PvY84tnFnlkOSp31MeqDlm0Z4k8kJzulETIgG6GJUhMhDXeGlMk+H8IvuWql2g9EVxBlfjOdy4iK2+xk/JAf9V472gjeHVI8mZjmnt11+tyOancRqnLK7kL+w2/wCxROLgtwKYJKUGGBKl5gBxM/o/yJy0zcJmrC/kmheHFtWlbXMXap7HB1WbZP15+WWfir4/bL0Dl8J5oL/WcsTmCd5/zQBwQcKZGW7lM6fve4tO3az1mUYv9fASAIg6cqkbnU1SyPHgotTdn6p7Z8CYUwtCI4oHalD3h1jUNQjeSUfhWy/w0JbMWleeV9Hx9wOsCtdmW9c4EuB1+WotRR58ED7CQmPy5zAwZslGCKhLwxHRIZzgiV0x/PfqYVpa9magQlXblZe0alg0O1cjE5t7WQmymaFWwf/4mVWThyNn9NmLUokUG3cWdrhZ0aBMxg9xr0/apJa4pByGFB/m8n+fy4TKm5It6+1X4Qm2auG+bvx9mCJQKOW85ALZqHnGQZ9T9ORMpxdUibAdKPfnAdZNj1hRrlX0dPlhfQrTw6QMsO7iQeKuQRj6RlkgWSNmeX+ZdcIzUi0g==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared