apiVersion: v1
kind: Service
metadata:
  name: td-backend
  namespace: traveldiscover
spec:
  selector:
    app: td-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
