apiVersion: v1
kind: Service
metadata:
  name: td-frontend-service
  namespace: default
spec:
  selector:
    app: td-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
